// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL0Udw8bJY64YJjXY6BP6KkiEVcwz9YAE',
    appId: '1:340567392458:android:e4aafc6ef36b37e5813433',
    messagingSenderId: '340567392458',
    projectId: 'ihzar-8294a',
    storageBucket: 'ihzar-8294a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzXx2PrFXizYsqwsnD4vgiwvTz678IXg',
    appId: '1:340567392458:ios:a43da4f12729c07c813433',
    messagingSenderId: '340567392458',
    projectId: 'ihzar-8294a',
    storageBucket: 'ihzar-8294a.firebasestorage.app',
    iosBundleId: 'com.ehzar.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAIMkqBCpHzBd067LXF37JMOuYh_zv87no",
      authDomain: "ihzar-8294a.firebaseapp.com",
      projectId: "ihzar-8294a",
      storageBucket: "ihzar-8294a.firebasestorage.app",
      messagingSenderId: "340567392458",
      appId: "1:340567392458:web:e08a5cf5dfaaf0fd813433");
}
